# Generated by Django 3.1.1 on 2020-09-21 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested',
            field=models.ManyToManyField(blank=True, related_name='user_requested', to=settings.AUTH_USER_MODEL),
        ),
    ]
