# Generated by Django 3.1.1 on 2020-09-21 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_requested'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='requested',
            new_name='requests',
        ),
    ]
